users/urls.py
from django.contrib import admin
from django.urls import path, include
from users_app import views

urlpatterns = [
    path('',views.index, name='index'),
    path('admin/', admin.site.urls),
    path('user_app/', include('users_app.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('special', views.special, name='special')

]

users_app/urls.py
from django.urls import path
from . import views

app_name = 'users_app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login,name='user_login')
]

users_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfile_Model(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfilio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

users_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile_Model


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfile_Form(forms.ModelForm):
    class Meta():
        model = UserProfile_Model
        fields = ('portfilio_site', 'profile_pic')

users_app/views.py
from django.shortcuts import render
from .forms import UserForm, UserProfile_Form


from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    return render(request, 'users_app/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse('You are logged in')


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfile_Form(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']


            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfile_Form()
    return render(request,'users_app/registration.html',
        context={'user_form':user_form,
                 'profile_form':profile_form,
                 'registered':registered })


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account is not active')
        else:
            print('Invalid Login Attempt')
            return HttpResponse('Thats not a valid Username or Password')
    else:
        return render(request,'users_app/login.html')

users_app/templates/users_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'index'%}">Home</a>
        <a class="navbar-item nav-link" href="{% url 'admin:index'%}">Admin</a>
        <a class="navbar-item nav-link" href="{% url 'users_app:register'%}">Register</a>

        {%if user.is_authenticated %}
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        {% else %}
          <a class="nav-link" href="{% url 'users_app:user_login'%}">Login</a>
        {% endif %}

      </div>
    </nav>

<div class="container">
    {% block body_block%}
    {% endblock %}
</div>



  </body>
</html>

users_app/templates/users_app/index.html
{% extends "users_app/base.html" %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h1>Welcome!</h1>
  </div>

</div>

{% endblock %}

users_app/templates/users_app/login.html
{% extends 'users_app/base.html'%}
{% block body_block%}

<div class="container">
  <div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'users_app:user_login'%}" method="post">
      {% csrf_token%}
      <label for="username">Username:</label>
      <input type="text" name="username" placeholder="Enter Username">

      <label for="password">Password:</label>
      <input type="password" name="password">

      <input type="submit" name="" value="Login">
    </form>

  </div>

</div>

{% endblock %}

users_app/templates/users_app/registration.html
{% extends "users_app/base.html"%}


{% block body_block%}

<div class="container">
  <div class="jumbotron">
    {% if registered %}
    <h1>You are signed in </h1>
    {% else %}
    <h1>Register Here </h1>
    <h3>Fill out the form below</h3>

    <form enctype="multipart/form-data" method="post">
      {% csrf_token %}
      {{ user_form.as_p}}
      {{ profile_form.as_p}}

      <input type="submit" name="" value="Register">

    </form>

    {% endif%}

  </div>

</div>

{%endblock%}